name: Prevent Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  check-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check if push is from a pull request
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "push" && "$GITHUB_HEAD_REF" == "" ]]; then
            echo "Direct pushes to 'main' are not allowed. Please use a pull request."
            exit 1
          else
            echo "Push is from a pull request. Proceeding."
          fi
