name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-CPP-500-LYN-5-2-rtype-noe.pereira.git"

jobs:
  prevent_direct_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check for Direct Push
        shell: bash
        run: |
          if [[ -z "$GITHUB_HEAD_REF" ]]; then
            echo "❌ Direct pushes to 'main' are not allowed. Please create a pull request."
            exit 1
          else
            echo "✅ Push is from a pull request. Proceeding."
