name: Test clang format

on:
  push:
    branches:
      - 'feature/fix-ci-cd'

jobs:
  clang_format_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Clang-Format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check Code Format
        id: clang_format
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror -style=file

  clang_format_fix:
    runs-on: ubuntu-latest
    needs: clang_format_check
    if: failure()
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Clang-Format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Apply Clang-Format Fixes
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format -i -style=file

      - name: Commit and Push Fixes
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "[ADD] auto-format code with clang-format"
          git push origin ${{ github.head_ref }}
