name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-CPP-500-LYN-5-2-rtype-noe.pereira.git"

jobs:
  check_direct_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Prevent Direct Push to Main
        run: |
          if [[ "$GITHUB_HEAD_REF" == "" ]]; then
            echo "Direct pushes to 'main' are not allowed. Please use a pull request."
            exit 1
          else
            echo "Push is from a pull request. Proceeding."
          fi

  build_and_verify:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake g++ make libconfig++-dev

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build R-Type
        run: cmake --build build

      - name: Verify Executables
        run: |
          test -f r-type_server || { echo "r-type_server not found!"; exit 1; }
          test -f r-type_client || { echo "r-type_client not found!"; exit 1; }

  push_to_mirror:
    if: github.event_name == 'push' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    needs: [build_and_verify]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Mirror Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
